version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
      - ./results:/app/results
    environment:
      - LLMEVAL_ENV=development
      - LLMEVAL_LOG_LEVEL=INFO
      - LLMEVAL_LITELLM_BASE_URL=http://llm-service:11434/api/generate
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    depends_on:
      - mlflow
    restart: unless-stopped
    networks:
      - llm-eval-network

  # MLflowサービスの追加
  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    ports:
      - "5000:5000"
    volumes:
      - ./mlflow:/mlflow
    environment:
      - MLFLOW_TRACKING_URI=http://localhost:5000
      - MLFLOW_BACKEND_STORE_URI=sqlite:///mlflow/mlflow.db
      - MLFLOW_DEFAULT_ARTIFACT_ROOT=file:///mlflow/artifacts
    command: mlflow server --host 0.0.0.0
    networks:
      - llm-eval-network

  # LLMサービス（Ollamaなど）と接続する場合のサンプル設定
  # llm-service:
  #   image: ollama/ollama:latest
  #   ports:
  #     - "11434:11434"
  #   volumes:
  #     - ollama-data:/root/.ollama
  #   networks:
  #     - llm-eval-network

networks:
  llm-eval-network:
    driver: bridge

volumes:
  mlflow:

# volumes:
#   ollama-data: